### ISSUE TITLE
【missing files】there are no files such as "optimal_run.py", "optimal_visualization.py", "capacity_run.py" et al.

### ISSUE THREAD

**Issue by RayX47** [barrelo89/Python-for-Paper#2]
Hi, I find there are missing files.

> Readme.md
In the part of **Running the code**,
but there are no files such as "optimal_run.py", "optimal_visualization.py", "capacity_run.py" et al.

Is this project incomplete to open source?

Thanks for your reply.

**Comment by barrelo89** [comment]
Hello,

Thank you for reporting the issue.

I added the mission files.

Thought they were uploaded.

Take care!
