### ISSUE TITLE
【missing function】TaskSizer、CostCalculator、BudgetBalanceCheck……

### ISSUE THREAD

**Issue by RayX47** [barrelo89/Python-for-Paper#4]
Excuse me, need your help again.

There is a new problem that missing some functions in "**optimal_run.py**".

such as _TaskSizer_、_CostCalculator_、_BudgetBalanceCheck_、_MereSW_、_ExpectedSW_、_PostSW_、_TimeVariantMoney_、_BudgetBalanceCheck_、_TimeVariantMoney_

THANK YOU VERY MUCH.

**Comment by barrelo89** [comment]
Hello, 
All the functions with which you have the problem are defined in ''function.py".

I guess as long as you have the 'function.py' in your directory where you are running the command window, it should work without an issue.

**Comment by RayX47** [comment]
> Hello,
> All the functions with which you have the problem are defined in ''function.py".
> 
> I guess as long as you have the 'function.py' in your directory where you are running the command window, it should work without an issue.

Excuse me, but I can't find the definition of "TaskSizer()" in 'function.py'.
The same problem is like "DataExtraction()","DataTrimming()".
Could you please check it out?

**Comment by RayX47** [comment]
would you please update the "function.py" again?
It updated in 2017.
![image](https://user-images.githubusercontent.com/35096520/94111576-d583c480-fe76-11ea-9cb9-90f48e4873f4.png)
`Traceback (most recent call last):
  File "F:\anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "F:\anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "F:\code\IEEE-Internet-of-Things-Journal-master\optimal_run.py", line 210, in SW
    greedy_result = SW1(tasks, providers, capacity)
  File "F:\code\IEEE-Internet-of-Things-Journal-master\optimal_run.py", line 28, in SW1
    task_size = TaskSizer(W_requesters)
NameError: name 'TaskSizer' is not defined
`

**Comment by barrelo89** [comment]
Hello again,

I updated 'function.py'.

Please check and let me know if you have some other issues.

Thanks
