### ISSUE TITLE
Seek Help

### ISSUE THREAD

**Issue by yaya-black** [barrelo89/Python-for-Paper#5]
Hello, I am a postgraduate student, and I saw your message on GitHub:Small Profits and Quick Returns: A Practical Social Welfare Maximizing Incentive Mechanisms for Deadline-sensitive Tasks in Crowdsourcing.But the data in the paper was encrypted,Some code needs to look at the data to help understand it.I hope you can provide me with the data, which will be of great help to my research. Thank you very much！

**Comment by barrelo89** [comment]
Hello @yaya-black,

Sorry for the late reply.

I haven't checked my repository for a while.

Could you let me know which data was encrypted?

I guess all the data is shared in this repository.
